/******************************************************************************/
/****              Generated by IBExpert 30/09/2024 19:17:39               ****/
/******************************************************************************/

/******************************************************************************/
/****     Following SET SQL DIALECT is just for the Database Comparer      ****/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE TBUSUARIOS (
    ID                       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    TIPO                     INTEGER DEFAULT 0 NOT NULL,
    USUARIO                  VARCHAR(32) NOT NULL,
    NOME                     VARCHAR(80) NOT NULL,
    SENHA                    VARCHAR(32) NOT NULL,
    SITUACAO                 INTEGER DEFAULT 1 NOT NULL,
    DATA_INCLUSAO            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    IDUSUARIO_INCLUSAO       INTEGER NOT NULL,
    DATA_ULT_ALTERACAO       TIMESTAMP,
    IDUSUARIO_ULT_ALTERACAO  INTEGER
);



/******************************************************************************/
/****                       Autoincrement generators                       ****/
/******************************************************************************/

ALTER TABLE TBUSUARIOS ALTER ID RESTART WITH 1;




/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE TBUSUARIOS ADD CONSTRAINT PK_TBUSUARIOS PRIMARY KEY (ID);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE TBUSUARIOS ADD CONSTRAINT FK_TBUSUARIOS_1 FOREIGN KEY (IDUSUARIO_INCLUSAO) REFERENCES TBUSUARIOS (ID) ON DELETE CASCADE;
ALTER TABLE TBUSUARIOS ADD CONSTRAINT FK_TBUSUARIOS_2 FOREIGN KEY (IDUSUARIO_ULT_ALTERACAO) REFERENCES TBUSUARIOS (ID) ON DELETE CASCADE;


/******************************************************************************/
/****                         Fields descriptions                          ****/
/******************************************************************************/

COMMENT ON COLUMN TBUSUARIOS.TIPO IS
'0 - DESENVOLVEDOR
1 - ADMINISTRADOR
2 - PROGRAMADOR
3 - GUEST(USUARIO SÓ VISUALIZACO)';

COMMENT ON COLUMN TBUSUARIOS.SITUACAO IS
'0 - INATIVO
1 - ATIVO';



/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/
