/******************************************************************************/
/****              Generated by IBExpert 30/09/2024 19:15:12               ****/
/******************************************************************************/

/******************************************************************************/
/****     Following SET SQL DIALECT is just for the Database Comparer      ****/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE TBEMPRESAS (
    ID                       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    CNPJ                     VARCHAR(20) NOT NULL,
    RAZAO_SOCIAL             VARCHAR(80) NOT NULL,
    NOME_FANTASIA            VARCHAR(80),
    CEP                      VARCHAR(10),
    ENDERECO                 VARCHAR(80),
    NUMERO                   VARCHAR(80),
    COMPLEMENTO              VARCHAR(80),
    BAIRRO                   VARCHAR(80),
    ESTADO                   VARCHAR(2),
    CIDADE                   VARCHAR(80),
    SITUACAO                 INTEGER DEFAULT 1 NOT NULL,
    DATA_INCLUSAO            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    IDUSUARIO_INCLUSAO       INTEGER NOT NULL,
    DATA_ULT_ALTERACAO       TIMESTAMP,
    IDUSUARIO_ULT_ALTERACAO  INTEGER
);



/******************************************************************************/
/****                       Autoincrement generators                       ****/
/******************************************************************************/

ALTER TABLE TBEMPRESAS ALTER ID RESTART WITH 1;




/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE TBEMPRESAS ADD CONSTRAINT PK_TBEMPRESAS PRIMARY KEY (ID);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE TBEMPRESAS ADD CONSTRAINT FK_TBEMPRESAS_1 FOREIGN KEY (IDUSUARIO_INCLUSAO) REFERENCES TBUSUARIOS (ID) ON DELETE CASCADE;
ALTER TABLE TBEMPRESAS ADD CONSTRAINT FK_TBEMPRESAS_2 FOREIGN KEY (IDUSUARIO_ULT_ALTERACAO) REFERENCES TBUSUARIOS (ID) ON DELETE CASCADE;


/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/
