/******************************************************************************/
/****              Generated by IBExpert 30/09/2024 19:18:16               ****/
/******************************************************************************/

/******************************************************************************/
/****     Following SET SQL DIALECT is just for the Database Comparer      ****/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE TBUSUARIOSXPERMISSOES (
    ID                       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    IDEMPRESA                INTEGER NOT NULL,
    IDUSUARIO                INTEGER NOT NULL,
    NOME_FRM                 VARCHAR(100) NOT NULL,
    SITUACAO                 INTEGER DEFAULT 0 NOT NULL,
    DATA_INCLUSAO            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    IDUSUARIO_INCLUSAO       INTEGER NOT NULL,
    DATA_ULT_ALTERACAO       TIMESTAMP,
    IDUSUARIO_ULT_ALTERACAO  INTEGER
);



/******************************************************************************/
/****                       Autoincrement generators                       ****/
/******************************************************************************/

ALTER TABLE TBUSUARIOSXPERMISSOES ALTER ID RESTART WITH 0;




/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE TBUSUARIOSXPERMISSOES ADD CONSTRAINT PK_TBUSUARIOSXPERMISSOES PRIMARY KEY (ID);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE TBUSUARIOSXPERMISSOES ADD CONSTRAINT FK_TBUSUARIOSXPERMISSOES_1 FOREIGN KEY (IDEMPRESA) REFERENCES TBEMPRESAS (ID) ON DELETE CASCADE;
ALTER TABLE TBUSUARIOSXPERMISSOES ADD CONSTRAINT FK_TBUSUARIOSXPERMISSOES_2 FOREIGN KEY (IDUSUARIO) REFERENCES TBUSUARIOS (ID) ON DELETE CASCADE;
ALTER TABLE TBUSUARIOSXPERMISSOES ADD CONSTRAINT FK_TBUSUARIOSXPERMISSOES_3 FOREIGN KEY (IDUSUARIO_INCLUSAO) REFERENCES TBUSUARIOS (ID) ON DELETE CASCADE;
ALTER TABLE TBUSUARIOSXPERMISSOES ADD CONSTRAINT FK_TBUSUARIOSXPERMISSOES_4 FOREIGN KEY (IDUSUARIO_ULT_ALTERACAO) REFERENCES TBUSUARIOS (ID) ON DELETE CASCADE;


/******************************************************************************/
/****                         Fields descriptions                          ****/
/******************************************************************************/

COMMENT ON COLUMN TBUSUARIOSXPERMISSOES.SITUACAO IS
'0 - NÃO PERMITIDO
1 - PERMITIDO';



/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/
